/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-04-19 19:34:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_002dus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <title>About Us - DoTask</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background-color: #f4f8fb;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container {\r\n");
      out.write("            max-width: 1100px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 40px 30px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container h2 {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            line-height: 1.8;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding-left: 0;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            line-height: 1.8;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-container ul li {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta h3 {\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            padding: 15px 35px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cta a:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-top: 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer a {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsiveness */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            h1 {\r\n");
      out.write("                font-size: 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .about-container {\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .about-container h2 {\r\n");
      out.write("                font-size: 28px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .cta h3 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .cta p {\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <h1>About Us</h1>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"about-container\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <h2>Who We Are</h2>\r\n");
      out.write("            <p>At DoTask, we provide a simple yet powerful task management platform that helps individuals and teams stay organized, increase productivity, and achieve their goals. Our platform is designed to meet the needs of both personal and team task management, helping users streamline their work processes with ease.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <h2>Our Mission</h2>\r\n");
      out.write("            <p>Our mission is to empower individuals and teams by providing an intuitive platform that enhances task management and simplifies collaboration. We believe that task management shouldn't be complex, which is why DoTask is built with simplicity and efficiency in mind.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <h2>Our Values</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><strong>Efficiency:</strong> Helping users accomplish more in less time.</li>\r\n");
      out.write("                <li><strong>Collaboration:</strong> Encouraging teamwork and seamless communication.</li>\r\n");
      out.write("                <li><strong>Transparency:</strong> Providing clear, actionable insights.</li>\r\n");
      out.write("                <li><strong>Innovation:</strong> Continuously evolving to meet the needs of our users.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cta\">\r\n");
      out.write("        <h3>Ready to Get Started?</h3>\r\n");
      out.write("        <p>Join thousands of users who are boosting their productivity with DoTask. Sign up today and start managing your tasks more efficiently.</p>\r\n");
      out.write("        <a href=\"register.jsp\">Get Started Now</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2025 DoTask. All Rights Reserved. | <a href=\"about-us.jsp\">About Us</a> | <a href=\"contact-us.jsp\">Contact Us</a></p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
